// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: pingpong.proto

package pingpong

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Ponger service

type PongerService interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingReply, error)
}

type pongerService struct {
	c    client.Client
	name string
}

func NewPongerService(name string, c client.Client) PongerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "pingpong"
	}
	return &pongerService{
		c:    c,
		name: name,
	}
}

func (c *pongerService) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PingReply, error) {
	req := c.c.NewRequest(c.name, "Ponger.Ping", in)
	out := new(PingReply)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ponger service

type PongerHandler interface {
	Ping(context.Context, *PingRequest, *PingReply) error
}

func RegisterPongerHandler(s server.Server, hdlr PongerHandler, opts ...server.HandlerOption) error {
	type ponger interface {
		Ping(ctx context.Context, in *PingRequest, out *PingReply) error
	}
	type Ponger struct {
		ponger
	}
	h := &pongerHandler{hdlr}
	return s.Handle(s.NewHandler(&Ponger{h}, opts...))
}

type pongerHandler struct {
	PongerHandler
}

func (h *pongerHandler) Ping(ctx context.Context, in *PingRequest, out *PingReply) error {
	return h.PongerHandler.Ping(ctx, in, out)
}
